package com.bbva.wallet.exeptions;

public enum ErrorCodes {
    INVALID_VALUE,DUPLICATED_VALUE, WRONG_METHOD,
    SAME_ACCOUNT_TRANSFER,OVER_LIMIT,INSUFFICIENT_FOUNDS,DIFFERENT_CURRENCY,
    INCORRECT_AMOUNT, ACCOUNT_DOESNT_EXIST, ACCOUNT_ALREADY_EXISTS
}
